### ISSUE TITLE
Sql file for php 

### ISSUE THREAD

**Issue by Bygizemli-tech** [ldzombie/-System-Android-RAT-Trojan#1]
hi is there sql file for web interface

**Comment by Wernersbach** [comment]
hi is there sql file for web interface

**Comment by smithveg** [comment]
Your question is not clear, please elaborate. Or you can give a scenario.

**Comment by Wernersbach** [comment]
the database file is missing. .sql

**Comment by Gccorg** [comment]
There is no databse File , So , Users can Login , Please Upload it

**Comment by ldzombie** [comment]
sql file added to www
